# Generated by Django 3.2.11 on 2022-04-09 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0001_initial'),
        ('proprio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noteresidence',
            name='idresidence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proprio.residence'),
        ),
        migrations.AddField(
            model_name='commande',
            name='idclient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client'),
        ),
        migrations.AddField(
            model_name='commande',
            name='idresidence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proprio.residence'),
        ),
        migrations.AddField(
            model_name='client',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ajoutdesejour',
            name='idcommande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.commande'),
        ),
    ]
