version: "3"

services:
  web:
    build:
      context: ./resiapi
      cache_from:
        - "${WEB_IMAGE}"
    image: "${WEB_IMAGE}"
    command: bash start.sh #gunicorn Resi_mysql.wsgi:application -c gunicorn.conf    
    volumes:
      - ./tmp/logs:/usr/src/resiapi/tmp
      - ./media:/usr/src/resiapi/media
      - ./media/client/image:/usr/src/resiapi/media/client/image
      - ./media/proprio/profile:/usr/src/resiapi/media/proprio/profile
    expose:
      - "8000"
    env_file: .env
    
  nginx:
    build: 
      context: ./production_mode/nginx
      cache_from:
        - "${NGINX_IMAGE}"
    image: "${NGINX_IMAGE}"
    ports:
      - "80:80"
      # - "443:443"
    expose:
      - "8000"
    volumes:
      - ./static:/usr/share/nginx/html/static # mount static files
    links:
      - web
    depends_on:
      - web
    restart: always
